//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloQatarWebPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloStoreReport
    {
        public int Id { get; set; }
        public System.DateTime Date { get ; set; }
        public decimal NetAmount { get; set; }
        public int QTY { get; set; }
        public int InvoiceCount { get; set; }
        public Nullable<int> VistorCount { get; set; }
    }
}
